
-- 10/30 订单表增加字段（父ID、厂家ID）
ALTER TABLE `t_cus_order`
ADD COLUMN `I_PARENT_ID`  bigint(20),
ADD COLUMN `I_FACTORY_ID`  bigint(20);

-- 09/26 订单结算统计表增加字段  -runtime
ALTER TABLE `T_SETTLEMENT_ORDER_DETAIL` ADD COLUMN `I_PAY_TYPE`  int(11);
UPDATE T_SETTLEMENT_ORDER_DETAIL a LEFT JOIN t_cus_order_pay b ON a.I_ORDER_ID = b.I_ORDER_ID  SET a.I_PAY_TYPE = 1 WHERE b.I_PAY_TYPE = 1 OR b.I_PAY_TYPE = 2;
UPDATE T_SETTLEMENT_ORDER_DETAIL a LEFT JOIN t_cus_order_pay b ON a.I_ORDER_ID = b.I_ORDER_ID  SET a.I_PAY_TYPE = 2 WHERE ISNULL(b.I_PAY_TYPE);


-- 用户表添加新字段  2017-08-23 runtime
ALTER TABLE `t_cus_info`
ADD COLUMN `S_INVITATION_PATH`  varchar(4000) NULL AFTER `I_WEIX_ID`;

-- 枚举添加数据--配送信息--运输方式  2017-08-23 runtime
INSERT INTO `t_whs_enum_tbl` (`I_ID`, `D_CREATE_DATE`, `D_MODIFY_DATE`, `I_DOMAIN_ID`, `I_ENUM_VALUE`, `I_REL_ENUM_ID`, `S_ENUM_CN_NAME`, `S_ENUM_COL_NAME`, `S_ENUM_NAME`, `S_ENUM_TBL_NAME`, `S_REFERENCE_NAME`, `S_REL_ENUM_NAME`, `S_REMARK`, `I_IS_ENABLED`, `I_MODULE_ID`) VALUES ('98', '2017-08-23 14:11:14', '2017-08-23 14:11:16', '1', '1', NULL, '运输方式', 'I_TRANSPORT_TYPE', '快递', 'T_CUS_ORDER_RETURN', NULL, NULL, NULL, '1', '1');
INSERT INTO `t_whs_enum_tbl` (`I_ID`, `D_CREATE_DATE`, `D_MODIFY_DATE`, `I_DOMAIN_ID`, `I_ENUM_VALUE`, `I_REL_ENUM_ID`, `S_ENUM_CN_NAME`, `S_ENUM_COL_NAME`, `S_ENUM_NAME`, `S_ENUM_TBL_NAME`, `S_REFERENCE_NAME`, `S_REL_ENUM_NAME`, `S_REMARK`, `I_IS_ENABLED`, `I_MODULE_ID`) VALUES ('99', '2017-08-23 14:11:14', '2017-08-23 14:11:16', '1', '1', NULL, '运输方式', 'I_TRANSPORT_TYPE', '货运', 'T_CUS_ORDER_RETURN', '', '', '', '1', '1');


-- 08/22 厂家返利相关模型修改 -runtime
-- 商品价格定义增加字段（一、二、三、四、五级返利）
ALTER TABLE `t_product_price`
ADD COLUMN `I_REBATE_ONE`  double,
ADD COLUMN `I_REBATE_TWO`  double,
ADD COLUMN `I_REBATE_THREE`  double,
ADD COLUMN `I_REBATE_FOUR`  double,
ADD COLUMN `I_REBATE_FIVE`  double;

-- 商品活动关联表增加字段（一、二、三、四、五级返利）
ALTER TABLE `T_ACTIVITY_PRODUCT_REL`
ADD COLUMN `I_REBATE_ONE`  double,
ADD COLUMN `I_REBATE_TWO`  double,
ADD COLUMN `I_REBATE_THREE`  double,
ADD COLUMN `I_REBATE_FOUR`  double,
ADD COLUMN `I_REBATE_FIVE`  double;

-- 订单详情增加字段（厂家返利金额）
ALTER TABLE `T_CUS_ORDER_DETAIL`
ADD COLUMN `S_REBATE_JSON`  varchar(1024);

-- 订单结算统计增加字段（厂家返利金额）
ALTER TABLE `T_SETTLEMENT_ORDER_DETAIL`
ADD COLUMN `S_REBATE_JSON`  varchar(1024);

-- 账户信息增加字段（厂家返利未到账）
ALTER TABLE `T_CUS_ACCOUNT_CONSUME`
ADD COLUMN `I_RECIVE_REBATE_MONEY`  double;
UPDATE T_CUS_ACCOUNT_CONSUME SET I_RECIVE_REBATE_MONEY = 0;

-- 增加表（提成/返利结算记录表）
CREATE TABLE `t_settlement_push_record` (
  `I_ID` bigint(20) NOT NULL,
  `D_CREATE_DATE` datetime NOT NULL,
  `D_MODIFY_DATE` datetime NOT NULL,
  `I_ACCOUNT_DETAIL_ID` bigint(20) DEFAULT NULL,
  `I_ORDER_ID` bigint(20) DEFAULT NULL,
  `I_PUSH_MONEY` double DEFAULT NULL,
  `I_REBATE_LEVEL` int(11) DEFAULT NULL,
  `I_SHOPKEEPER_ID` bigint(20) DEFAULT NULL,
  `I_TYPE` int(11) DEFAULT NULL,
  `I_UNIT_PRICE` double DEFAULT NULL,
  PRIMARY KEY (`I_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
